name: SonarCloud Scan

on:
  workflow_dispatch:
    inputs:
      sonar_org:
        required: true
        type: string
      sonar_project_key:
        required: true
        type: string
      branch:
        required: false
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ inputs.sonar_org }}
            -Dsonar.projectKey=${{ inputs.sonar_project_key }}
